name: Trigger TF Script Update UCA Solution Workflow

on:
  workflow_dispatch:

permissions:
    actions: write

jobs:
    trigger:
        runs-on: ubuntu-latest
        container:
            image: node:latest
        steps:
          - name: Generate an access token for REST API
            id: generate-token
            uses: actions/create-github-app-token@v1           
            with:
              app-id: ${{ secrets.GH_ACCESS_TOKEN_APP_ID }}
              private-key: ${{ secrets.GH_ACCESS_TOKEN_APP_PK }}
              owner: "fp-core-experience"
              github-api-url: ${{ vars.GHES_API_URL }}
          - name: Trigger Workflow in Metadata Repository
            run: |
              repo_name="fp-core-experience/btp-quick-setup-metadata"  
              event_type="trigger-workflow" 
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ steps.generate-token.outputs.token}}" \
                ${{ vars.GITHUB_API_URL }}/repos/$repo_name/dispatches \
                -d "{\"event_type\": \"$event_type\"}"
